"""Creating user_db tables

Revision ID: 0d738ebc474c
Revises: 
Create Date: 2026-02-23 06:53:56.697953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d738ebc474c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_pwd', sa.String(), nullable=True),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('is_organization', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.Column('subscription_start', sa.Date(), nullable=True),
    sa.Column('subscription_end', sa.Date(), nullable=True),
    sa.Column('max_requests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_organization'), 'users', ['is_organization'], unique=False)
    op.create_index(op.f('ix_users_organization_name'), 'users', ['organization_name'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('user_req_logs',
    sa.Column('req_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('req_received', sa.Boolean(), nullable=True),
    sa.Column('req_processed', sa.Boolean(), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('task', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('req_id')
    )
    op.create_index(op.f('ix_user_req_logs_req_id'), 'user_req_logs', ['req_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_req_logs_req_id'), table_name='user_req_logs')
    op.drop_table('user_req_logs')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_organization'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
